pkg_name=PKG_NAME
pkg_origin=ssd
pkg_version=FIXME
pkg_maintainer="Steven Danna <steve@chef.io>"
pkg_description=FIXME
pkg_upstream_url=FIXME
pkg_license=(FIXME)
pkg_source=FIXME
pkg_shasum=FIXME
pkg_deps=(core/glibc)
pkg_build_deps=(core/gcc core/make)
pkg_include_dirs=(include)
pkg_lib_dirs=(lib)
pkg_bin_dirs=(bin)
